apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-manual-pv
  namespace: cnpg-system
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  hostPath:
    path: /mnt/data  # Change this path to match your setup
  # For AWS EBS, you should use `awsElasticBlockStore` instead of `hostPath`
  # awsElasticBlockStore:
  #   volumeID: vol-0abcd1234efgh5678
  #   fsType: ext4
  #   partition: 1

