apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-manual-pvc
  namespace: cnpg-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2

