apiVersion: v1
kind: Service
metadata:
  name: polls-service
spec:
  type: LoadBalancer
  selector:
    app: polls
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30001
